account/urls.py
from django.urls import path
from .views import users_list, user_profile, follow_unfollow, follow_request_requested, accept, direct, my_directs_view, followerings, register, user_login, changepass, loggedout, Edit_Profile
from django.views.generic import TemplateView

app_name = 'account'

urlpatterns = [
    path('users_list/', users_list, name='users_list'),
    path('users_profile/<int:id>/', user_profile, name='user_profile'),
    path('editprofile/', Edit_Profile, name='editprofile'),
    path('changepass/', changepass, name='changepassword'),
    path('login/', user_login, name='login'),
    path('logout/', loggedout, name='logout'),
    path('register/', register, name='register'),
    path('follow_unfollow/', follow_unfollow, name='follow_unfollow'),
    path('follow_request_requested/', follow_request_requested, name='follow_request_requested'),
    path('accept/<int:id>/<str:identifier>/', accept, name='accept'),
    path('direct/<int:id>/', direct, name='direct'),
    path('mydirects/', my_directs_view, name='my_directs'),
    path('followerings/<int:id>/<str:identifier>/', followerings, name='followerings'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
	path('room/', views.course_chat_room, name='course_chat_room'),
]

new_site_3/urls.py
from new_site_3 import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base.html'), name='base'),
    path('users/', include('account.urls', namespace='account')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('story/', include('story.urls', namespace='story')),
    path('chat/', include('chat.urls', namespace='chat')),
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models

# Create your models here.

chat/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required


@login_required
def course_chat_room(request):
    #try:
        # retrieve course with given id joined by the current user
        #course = request.user.courses_joined.get(id=course_id)
    #except:
        # user is not a student of the course or course does not exist
        #return HttpResponseForbidden()
    return render(request, 'chat/room.html', {'course': 69})

chat/templates/chat/room.html
{% extends 'base.html' %}
{% load static %}


{% block script %}
				<style>
					div#sender { float: left; width: 80%; font-size: 15px; border-radius: 5px; box-shadow: 0 0 12px #3CFF9D; margin: 15px auto 15px auto; text-align: justify; padding: 8px; position: relative; }
					div#reciever { float: left; width: 80%; font-size: 15px; border-radius: 5px; box-shadow: 0 0 12px #C55FC5; margin: 15px auto 15px auto; text-align: justify; padding: 8px; position: relative; }
					p { font-family: Arial;}
					span#lastlogin { font-size: 13px; }
					span#commentdate { font-size: 10px; }
					div#nothing {float: left; width: 15%; margin: 10px auto auto 20px}
					pre {font-family: B Nazanin }
				</style>
{% endblock %}

{% block content %}
		   <!-- {{obj.last_login|time:"g:i:s P" }} --> 
		<div style="background-color: ; height: auto; width: 1200px; margin-left: 100px">
			<div style="background-color: ; width: 400px; margin-left: 480px">
				<img src="{% if obj.prof_image %}{{obj.prof_image.url}}{% else %}{% static 'images/image_not_found.jpg' %}{% endif %}"  
											style="width: 60px; height: 60px; border-radius: 30px; float: ; margin: 10px auto 10px 60px"> 
											<br>
											<span id="lastlogin">last Onlined :  {{obj.last_logedout|date:"D j/M/Y" }} - {{obj.last_logedout|time:"P" }}</span>
			</div>
			<div id="chat" style=" height: 350px; overflow: scroll; margin-top: 20px; box-shadow: 0 0 8px blue">
				{% if results != False %}
					{% for chat in results %}
					
						<div id="nothing" >
								{{chat.user_from.username}}:<br>
								<span id="commentdate">At : " {{chat.created|date:"j/M/Y" }} - {{chat.created|time:"g:i" }} "</span>
						</div>
						<div id="{% if request.user == chat.user_from %}sender{% else %}reciever{% endif %}" ><pre>{{chat.text}}</pre></div>
					{% endfor %}
				{% else %}
				
				{% endif %}
			</div>
			
			<div id="chat-input" style=" margin-top: 10px; margin-bottom: 30px">
				<input id="chat-message-input" type="text" class="form-control" style=" width: 100%">
				<input id="chat-message-submit" type="submit" value="Send" class="btn btn-primary btn-block" style="margin-top: 10px">
			</div>
		</div>
		
		

			
			
{% endblock content %}

{% block footer %}	

{% endblock footer %}



{% block prediction %} 

								var url = 'ws://' + window.location.host + '/ws/chat/room/69' ;
								var chatSocket = new WebSocket(url);
								
								chatSocket.onmessage = function(e) {
												var data = JSON.parse(e.data);
												var message = data.message;
												var $chat = $('#chat');
												
												$chat.append('<div class="message">' + message + '</div>');
												$chat.scrollTop($chat[0].scrollHeight);
																	};
								chatSocket.onclose = function(e) {
								console.error('Chat socket closed unexpectedly');
																};
	
								var $input = $('#chat-message-input');
								var $submit = $('#chat-message-submit');
								var $chat = $('#chat');
								
								$submit.click(function() {
											var message = $input.val();
											if(message) {
												// send message in JSON format
												chatSocket.send(JSON.stringify({'message': message}));
												
												// clear input
												$input.val('');
												
												// return focus
												$input.focus();
														}
																	});
								
														
														
								
								$input.focus();
								$input.keyup(function(e) {
											if (e.which === 13) {
											
											// submit with enter / return key
											$submit.click();
																}
														});
								

							
{% endblock prediction %}
							
$submit.click(function() {
																var message = $input.val();
																if(message) {
																
																// send message in JSON format
																$.post("{% url 'account:direct' obj.id %}", {msg: message}, function(data){
																	if (data['status'] == 'ok')
																			{
																			// clear input
																			$input.val('');
																			
																			// return focus
																			$input.focus();
																			
																			// append message to direct
																			$chat.append('<div id="nothing">{{request.user.username}} :<br><span id="commentdate">At : " ' + data['time'] + ' "</span></div><div id="sender" ><pre>' + message + '</pre></div> </div>');
																			$chat.scrollTop($chat[0].scrollHeight);
																			
																			}
		
																										});
																																
																

																		};
														});