account/urls.py
from django.urls import path
from .views import users_list, user_profile, follow_unfollow, follow_request_requested, accept, direct, my_directs_view, followerings, register, user_login, changepass, loggedout, Edit_Profile
from django.views.generic import TemplateView

app_name = 'account'

urlpatterns = [
    path('users_list/', users_list, name='users_list'),
    path('users_profile/<int:id>/', user_profile, name='user_profile'),
    path('editprofile/', Edit_Profile, name='editprofile'),
    path('changepass/', changepass, name='changepassword'),
    path('login/', user_login, name='login'),
    path('logout/', loggedout, name='logout'),
    path('register/', register, name='register'),
    path('follow_unfollow/', follow_unfollow, name='follow_unfollow'),
    path('follow_request_requested/', follow_request_requested, name='follow_request_requested'),
    path('accept/<int:id>/<str:identifier>/', accept, name='accept'),
    path('direct/<int:id>/', direct, name='direct'),
    path('mydirects/', my_directs_view, name='my_directs'),
    path('followerings/<int:id>/<str:identifier>/', followerings, name='followerings'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
	path('room/', views.course_chat_room, name='course_chat_room'),
]

new_site_3/urls.py
from new_site_3 import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='base.html'), name='base'),
    path('users/', include('account.urls', namespace='account')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('story/', include('story.urls', namespace='story')),
    path('chat/', include('chat.urls', namespace='chat')),
]
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new_site_3/templates/base.html
{% load static %}


<html> 
	<header>
		<title> {% block title %} Base blog {% endblock %}</title>
		<link href="{% static 'css/new1.css' %}" rel="stylesheet" type="text/css">
		
		<style>#main:hover{ text-decoration: none; color: #DADADA} #mainpage:hover{ color: #DFDFDF;text-decoration: none;} #main { color: white; font-size: 14px; }
		#articlepost {color: #920A7D; font-size: 22px;} #articlepost:hover{ color: #CB0EAE; text-decoration: none;}
		#tags {font-size: 13px; color: #7A7A7A; } #tags:hover {text-decoration: none; color: black}	
		</style>
		
		
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<!-- <script src="{% static 'js/jQuery.js' %}"></script> -->
		<!-- <script src="{% static 'js/popper.min.js' %}"></script> -->
		<script src="{% static 'js/bwootstrap.min.js' %}"></script>	
		
		{% block script %}
				
		{% endblock %}
		
		
	</header>
	<body>
		<div class="container-fluid">

			<div class="row">
				<div id="navbar" class="col-xl-11" style="background-color: #863186; box-shadow:0 0 12px #3E6A6C; margin-left: 50px; margin-top:1px">{% include "navbar.html" %}</div>
				<div id="content" class="col-xl-11" style="background-color: #F3DEF3; height: auto; margin-left: 50px; margin-top: 10px; border-radius: 20px">					
					{% block content %}
						
					{% endblock %}
				</div>
				
				{% block footer %}		
					<div id="footer" class="col-xl-11" style="background-color: #F3DEF3; height: 250px; margin-left: 50px; margin-top: 10px; border-radius: 10px">
					
					</div>
				{% endblock %}
				
				<script > 		
					$(document).ready(function() {
						 {% block domready %} 
							
							
							$.ajaxSetup({
								  data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
								});
								  
							{% block prediction %} 
											
							{% endblock prediction %}		
											
							$('.likew').click(function(e){
								
								e.preventDefault();
								$.post("/", {id:$(this).data('id'), action:$(this).data('action')},
																function(data){if (data['status']=='ok'){
																		var pre_action = $('.likew').data('action');
																		
																		$('.likew').text(pre_action=='like' ? 'DisLike' : 'Like');
																		$('.likew').data('action', pre_action=='like'? 'dislike' : 'like');
																		}}
																		);
								});
							
							$('.likee').click(function(){
							$('p').css("color", "yellow");
							$('h2').animate({opacity: '0.2'}, 2000);
							});
							
							$('#leko').click(function(e){
								
								e.preventDefault();
								$.get("/", {id:5, act:13}, function(data){$('#leko').text(data['state']);
																									$('span').text(data['nor']);			
																									$('#kil').append(data['loginf']);	
																									$('#id_username').addClass('form-control');
																									$('#id_password').addClass('form-control');
																										});
																										
								});
							
							
						 {% endblock %}
											});
					 
		</script>
			</div>

		</div>

	</body>

</html>

new_site_3/templates/navbar.html
{% load static %}

{% block script %}
			
			<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
			
			<script  src="{% static 'js/jquery.js' %}"></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/bwootstrap.min.js' %}"></script>
		
{% endblock %}

<nav class="navbar navbar-expand-xl navbar-dark  mb-1" >
				
				<a href="{% url 'account:users_list' %}"> All Users </a>
				
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarCollapse" style="margin-top: 10px">
					{% if user.is_authenticated %}
						<ul class="navbar-nav ml-auto">
							<li class="nav-item">
								<a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									{{ user.username }}
								</a>
								<div class="dropdown-menu dropdown-menu-right"	aria-labelledby="userMenu">
									<a class="dropdown-item" href="{% url 'account:changepassword' %}">Change password</a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="{% url 'account:logout' %}"> Log Out</a>
								</div>
							</li>
						</ul>
					{% else %}
						<form class="form-inline ml-auto">
							<a id="main" href="{% url 'account:login' %}" style=""> Log In  </a><pre style="margin-top: 30px; color: white; height: 30px"> / </pre><a id="main" href="{% url 'account:register' %}" style="">  Sign up</a>
						</form>
					{% endif %}
				</div>
			</nav>